export const GET_USERS = 'GET_USERS';
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const REQUEST_USERS = 'REQUEST_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_RESOURCES_REQUESTED = 'GET_RESOURCES_REQUESTED';
export const REQUEST_RESOURCES = 'REQUEST_RESOURCES';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const GET_RESOURCES_FAIL = 'GET_RESOURCES_FAIL';
